name: GH Actions demo

on: [pull_request_target]
jobs:
  Print-Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo echo $SOME_SECRET
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
